documentation/build.sh
documentation/source/includes/_open_banking.md.erb
documentation/source/includes/partials_open_banking/_disclosure_fees_interest_rates.md.erb
documentation/source/includes/partials_open_banking/_open_banking_fase1_apis.md.erb
documentation/source/index.html.md.erb
documentation/source/layouts/layout.erb
documentation/source/swagger/swagger_consents_apis.yaml
documentation/source/swagger/swagger_resources_apis.yaml

Implementação da página de valores e taxas no menu da API - Produtos e Serviços

Página de valores e taxas no menu da API - Produtos e Serviços

---

documentation/source/dictionary/personal_financial_relation.csv
documentation/source/dictionary/personal_identification.csv
documentation/source/dictionary/personal_qualification.csv
documentation/source/swagger/parts/schemas/customers_apis/PersonalFinancialRelationData.yaml
documentation/source/swagger/parts/schemas/customers_apis/PersonalIdentificationData.yaml
documentation/source/swagger/parts/schemas/customers_apis/PersonalProcurator.yaml
documentation/source/swagger/parts/schemas/customers_apis/PersonalQualificationData.yaml
documentation/source/swagger/parts/schemas/enum/EnumMaritalStatusCode.yaml
documentation/source/swagger/parts/schemas/enum/EnumProcuratorsTypePersonal.yaml
documentation/source/swagger/parts/schemas/enum/EnumProductServiceType.yaml

CUST-PN-038
CUST-PN-039
CUST-PN-040
CUST-PN-041
CUST-PN-042
CUST-PN-043
CUST-PN-044
CUST-PN-045
CUST-PN-046
CUST-PN-047
CUST-PN-048
CUST-PN-049
CUST-PN-050

[MIR-70] Correções da planilha Customers PN enviada pelo GT

---

documentation/source/swagger/parts/schemas/invoice_financings_apis/InvoiceFinancingsBalloonPayment.yaml
documentation/source/swagger/parts/schemas/invoice_financings_apis/InvoiceFinancingsContract.yaml
documentation/source/swagger/parts/schemas/invoice_financings_apis/InvoiceFinancingsContractInterestRate.yaml
documentation/source/swagger/parts/schemas/invoice_financings_apis/InvoiceFinancingsContractedFee.yaml
documentation/source/swagger/parts/schemas/invoice_financings_apis/InvoiceFinancingsContractedWarranty.yaml
documentation/source/swagger/parts/schemas/invoice_financings_apis/InvoiceFinancingsFinanceCharge.yaml
documentation/source/swagger/parts/schemas/invoice_financings_apis/InvoiceFinancingsInstalments.yaml
documentation/source/swagger/parts/schemas/invoice_financings_apis/InvoiceFinancingsPayments.yaml
documentation/source/swagger/parts/schemas/invoice_financings_apis/InvoiceFinancingsReleases.yaml
documentation/source/swagger/parts/schemas/invoice_financings_apis/InvoiceFinancingsTaxesOverParcel.yaml
documentation/source/swagger/parts/schemas/invoice_financings_apis/InvoiceFinancingsWarranties.yaml
documentation/source/swagger/parts/schemas/invoice_financings_apis/OverParcelPayments.yaml

[MIR-124] - retirada do item '- NA' no documentation/source/swagger/parts/schemas/invoice_financings_apis/InvoiceFinancingsInstalments.yaml

 [MIR-124] - retirada do item '- NA' no documentation/source/swagger/parts/schemas/invoice_financings_apis/InvoiceFinancingsInstalments.yaml

---

documentation/source/dictionary/business_qualification.csv
documentation/source/swagger/parts/schemas/customers_apis/BusinessInformedPatrimony.yaml

[MIR-132] - correção do campo Year no Businness/Qualification (Swagger e Dicionario de dados)

[MIR-132] - correção do campo Year no Businness/Qualification (Swagger e Dicionario de dados)

---

documentation/source/swagger/parts/schemas/customers_apis/BusinessIdentificationData.yaml

[MIR-113] - Correção de descrição do campo accounts - Swagger BusinessIdentificationData.yaml

[MIR-113] - Correção de descrição do campo accounts - Swagger BusinessIdentificationData.yaml

---

documentation/source/dictionary/credit_cards_accounts_bill.csv
documentation/source/swagger/parts/schemas/credit_cards_apis/CreditCardAccountsBillsData.yaml
documentation/source/swagger/parts/schemas/credit_cards_apis/CreditCardAccountsBillsFinanceCharge.yaml
documentation/source/swagger/parts/schemas/credit_cards_apis/CreditCardAccountsBillsPayment.yaml
documentation/source/swagger/parts/schemas/enum/EnumCreditCardAccountsBillingValueType.yaml
documentation/source/swagger/parts/schemas/enum/EnumCreditCardAccountsPaymentMode.yaml

[MIR-115] - Alterar OAS e dicionário de GET /accounts/{creditCardAccountId}/bills

[MIR-115] - Alterar OAS e dicionário de GET /accounts/{creditCardAccountId}/bills

---

documentation/source/dictionary/business_qualification.csv

[MIR-145] - Correçoes no Business_qualification.csv
Ajustes:
em nome de atributos: lowerCamelCase 
retirando validação que permitia nulo em campos

[MIR-145] - Correçoes no Business_qualification.csv

---

documentation/source/swagger/parts/parameters/PageSize.yaml
tatus

[MIR-155] - correção de máximo de paginas para 1000 (PageSize.yaml)

[MIR-155] - correção de máximo de paginas para 1000 (PageSize.yaml)

---

.github/workflows/build.yml
documentation/build.sh
documentation/source/swagger/swagger_admin_apis.yaml
documentation/source/swagger/swagger_channels_apis.yaml
documentation/source/swagger/swagger_common_apis.yaml
documentation/source/swagger/swagger_products_services_apis.yaml

Alterando a versao das apis da fase 1 de 1.0.0-rc5.2 para 1.0.0

Alterando a versao das apis da fase 1 de 1.0.0-rc5.2 para 1.0.0

---

documentation/source/includes/release_notes/releasenotes_v1.0.0.html.md.erb
documentation/source/layouts/layout.erb

[MIR-188]  Inclusão de texto para ficar mais claro que a versão 1.0.0 é referente ao Portal + inclusão de observação sobre não alterações dos swaggers e dicionarios de dados da fase 1

[MIR-188]  Inclusão de texto "versao portal 1.0.0" + observação do release notes

---

documentation/source/includes/partials_security_guide/_guia_usuario_instituicao_receptora.md.erb
documentation/source/includes/partials_security_guide/_guia_usuario_instituicao_transmissora.md.erb

Itens alterados:
- Segurança / Guia do usuário: Instituição Transmissora
- Segurança / Guia do usuário: Instituição Receptora ou Iniciadora de Pagamentos

[MF3-41] Alterações de texto e inclusão de links em 2 submenus de segurança

---

documentation/source/includes/partials_open_banking/_open_banking_fase4_apis.md.erb
documentation/source/swagger/parts/_open_banking_fase4_apis_part.yml
documentation/source/swagger/swagger_capitalization_bonds_apis.yaml
documentation/source/swagger/swagger_open_banking_fase4_apis.yml

ORB-567 components/schemas fulfilled for investments

ORB-567 components/schemas fulfilled for investments

---

documentation/source/dictionary/capitalizationBondsGetProducts_v1.csv
documentation/source/dictionary/investmentsGetFixedIncomeBank_v1.csv
documentation/source/dictionary/investmentsGetFixedIncomeCredit_v1.csv
documentation/source/dictionary/investmentsGetTreasure_v1.csv
documentation/source/dictionary/investmentsGetVariableIncome_v1.csv
documentation/source/includes/partials_open_banking/_open_banking_fase4_apis.md.erb
documentation/source/swagger/parts/_investments_apis_part.yml
documentation/source/swagger/parts/_open_banking_fase4_apis_part.yml
documentation/source/swagger/parts/schemas/investments_apis/InvestmentsFixedIncomeBank.yaml
documentation/source/swagger/parts/schemas/investments_apis/InvestmentsFixedIncomeCredit.yaml
documentation/source/swagger/parts/schemas/investments_apis/InvestmentsTreasure.yaml
documentation/source/swagger/parts/schemas/investments_apis/InvestmentsVariableIncome.yaml
documentation/source/swagger/swagger_investments_apis.yaml
documentation/source/swagger/swagger_open_banking_fase4_apis.yml

ORB-567 spectral lint warnings fixed #2

ORB-567 spectral lint warnings fixed #2

---

documentation/source/swagger/parts/_acquiring_services_apis_part.yml
documentation/source/swagger/parts/_exchange_apis_part.yml
documentation/source/swagger/parts/_investments_apis_part.yml
documentation/source/swagger/parts/_pension_apis_part.yml

ORB-1079 - Ajustar numeração das versões das APIs de FASE 4A no Swagger

fix(Câmbio | Credenciamento | Investimentos | Previdência): ORB-1079 - Ajustar numeração das versões swagger

---

documentation/source/swagger/parts/schemas/customers_apis/EconomicActivity.yaml

Adicionada restrição na descrição do campo **isMain** em *data/economicActivities/isMain*  da API de Dados Cadastrais no endpoint GET /business/qualifications;

fix(Dados Cadastrais): ORB-1147 - Atualizar restrição de campo

---

documentation/source/swagger/parts/schemas/financings_apis/FinancingsContract.yaml

Atualizado pattern e descrição do campo `firstInstalmentDueDate` do objeto FinancingsContract.

fix(OC_Financiamentos): ORB-1203 - Revisão da opcionalidade do campo firstInstalmentDueDate

---

documentation/source/swagger/parts/schemas/financings_apis/FinancingsContract.yaml

Atualizado pattern e descrição do campo `dueDate` do objeto FinancingsContract.

fix(OC_Financiamentos): ORB-1204 - Revisão da opcionalidade do campo dueDate

---

documentation/source/swagger/parts/schemas/financings_apis/FinancingsFeeOverParcel.yaml

Atualizada descrição do campo `feeCode` do objeto FinancingsFeeOverParcel.

fix(OC_Financiamentos): ORB-1206 - Revisão da opcionalidade do campo feeCode

---

documentation/source/dictionary/customersGetBusinessQualifications_v1.csv
documentation/source/dictionary/customersGetPersonalQualifications_v1.csv
documentation/source/dictionary/paymentsGetConsentsConsentId_v1.csv
documentation/source/dictionary/paymentsGetPixPaymentsPaymentId_v1.csv
documentation/source/dictionary/paymentsPatchPixPayments_v1.csv
documentation/source/dictionary/paymentsPostConsents_v1.csv
documentation/source/dictionary/paymentsPostPixPayments_v1.csv
documentation/source/includes/partials_open_banking/_open_banking_fase2_apis.md.erb
documentation/source/includes/partials_open_banking/_open_banking_fase3_apis.md.erb
documentation/source/includes/partials_open_banking/_open_banking_fase4_apis.md.erb
documentation/source/swagger/parts/schemas/customers_apis/EconomicActivity.yaml
documentation/source/swagger/swagger_acquiring_services_apis.yaml
documentation/source/swagger/swagger_exchange_apis.yaml
documentation/source/swagger/swagger_investments_apis.yaml
documentation/source/swagger/swagger_payments_apis.yaml
documentation/source/swagger/swagger_pension_apis.yaml

… tipo string com as devidas padronizaçoes (pattern, minLength e maxLength).

fix(Dados Cadastrais): ORB-1162 - Trocar campos do tipo double para o tipo string com as devidas padronizaçoes (pattern, minLength e maxLength).

---

documentation/source/swagger/parts/schemas/customers_apis/InformedRevenue.yaml

fix(Dados Cadastrais): ORB-1188 - Adicionar quebra de linha na descrição do campo frequencyAdditionalInfo

---

documentation/source/swagger/parts/schemas/customers_apis/BusinessPostalAddress.yaml

fix(Dados Cadastrais): ORB-1195 - Alterar descriçao do campo BusinessPostalAddress.townName

---

documentation/source/dictionary/customersGetBusinessIdentifications_v1.csv
documentation/source/swagger/parts/schemas/customers_apis/BusinessPostalAddress.yaml

fix(Dados Cadastrais): ORB-1195 - Ajustar campo townName no dicionario de dados

---

documentation/source/swagger/parts/schemas/unarranged_account_overdraft_apis/UnarrangedAccountOverdraftContractData.yaml

BCLOG-F02-031
GET /contracts/{contractId}
DueDate
Formato: ^(\d{4})-(1[0-2]|0?[1-9])-(3[01]|[12][0-9]|0?[1-9])$
incluir na restrição e na definição: "Caso a instituição não possua a informação para compartilhamento, informar NA"
Incluir no formato/pattern o NA

feat(OC_Adiantamento): ORB-1219 - Adicionando restrição no campo dueDate

---

documentation/source/swagger/parts/schemas/unarranged_account_overdraft_apis/UnarrangedAccountOverdraftFeeOverParcel.yaml

BCLOG-F02-148
GET /contracts/{contractId}/paymentsfeeCodeincluir na restrição: "Caso a instituição não possua a informação para compartilhamento, informar NA"

feat(OC_Adiantamento a Depositantes): ORB-1221 - Adicionando restrição no campo feeCode
